### ISSUE TITLE
`Orders` are missing from the query structure

### ISSUE THREAD

**Issue by IronistM** [IronistM/R_Google_Analytics#5]

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)
- Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/IronistM/R_Google_Analytics/5/1ef1e6ec-7390-4121-9481-288a503f709a/8f910f79-a13f-45e5-b324-a70b216bae7e) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>
